# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filesendtest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ilesendtest.proto\x12\x0c\x66ilesendtest\"P\n\x11\x46ileSendTestParam\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ilesize\x18\x02 \x01(\x05\x12\r\n\x05index\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"M\n\x19\x46ileSendTestResponseParam\x12\r\n\x05reply\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x12\n\nrecvedsize\x18\x03 \x01(\x05\x32u\n\x13\x46ileSendTestService\x12^\n\x0c\x46ileSendTest\x12\x1f.filesendtest.FileSendTestParam\x1a\'.filesendtest.FileSendTestResponseParam\"\x00(\x01\x30\x01\x62\x06proto3')



_FILESENDTESTPARAM = DESCRIPTOR.message_types_by_name['FileSendTestParam']
_FILESENDTESTRESPONSEPARAM = DESCRIPTOR.message_types_by_name['FileSendTestResponseParam']
FileSendTestParam = _reflection.GeneratedProtocolMessageType('FileSendTestParam', (_message.Message,), {
  'DESCRIPTOR' : _FILESENDTESTPARAM,
  '__module__' : 'filesendtest_pb2'
  # @@protoc_insertion_point(class_scope:filesendtest.FileSendTestParam)
  })
_sym_db.RegisterMessage(FileSendTestParam)

FileSendTestResponseParam = _reflection.GeneratedProtocolMessageType('FileSendTestResponseParam', (_message.Message,), {
  'DESCRIPTOR' : _FILESENDTESTRESPONSEPARAM,
  '__module__' : 'filesendtest_pb2'
  # @@protoc_insertion_point(class_scope:filesendtest.FileSendTestResponseParam)
  })
_sym_db.RegisterMessage(FileSendTestResponseParam)

_FILESENDTESTSERVICE = DESCRIPTOR.services_by_name['FileSendTestService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILESENDTESTPARAM._serialized_start=36
  _FILESENDTESTPARAM._serialized_end=116
  _FILESENDTESTRESPONSEPARAM._serialized_start=118
  _FILESENDTESTRESPONSEPARAM._serialized_end=195
  _FILESENDTESTSERVICE._serialized_start=197
  _FILESENDTESTSERVICE._serialized_end=314
# @@protoc_insertion_point(module_scope)
