# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import filesendtest_pb2 as filesendtest__pb2


class FileSendTestServiceStub(object):
    """interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileSendTest = channel.stream_stream(
                '/filesendtest.FileSendTestService/FileSendTest',
                request_serializer=filesendtest__pb2.FileSendTestParam.SerializeToString,
                response_deserializer=filesendtest__pb2.FileSendTestResponseParam.FromString,
                )


class FileSendTestServiceServicer(object):
    """interface
    """

    def FileSendTest(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileSendTestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FileSendTest': grpc.stream_stream_rpc_method_handler(
                    servicer.FileSendTest,
                    request_deserializer=filesendtest__pb2.FileSendTestParam.FromString,
                    response_serializer=filesendtest__pb2.FileSendTestResponseParam.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'filesendtest.FileSendTestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileSendTestService(object):
    """interface
    """

    @staticmethod
    def FileSendTest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/filesendtest.FileSendTestService/FileSendTest',
            filesendtest__pb2.FileSendTestParam.SerializeToString,
            filesendtest__pb2.FileSendTestResponseParam.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
